### ISSUE TITLE
Issues with next version of ggplot2

### ISSUE THREAD

**Issue by thomasp85** [mdsumner/ggpolypath#6]
Hi

We preparing the next release of ggplot2 and our reverse dependency checks show that your package is failing with the new version. Looking into it we see that the issues are due to our switch to using the `linewidth` aesthetic for stroke width instead of `size`. Please see https://www.tidyverse.org/blog/2022/08/ggplot2-3-4-0-size-to-linewidth/ for more info on this.

You can install the release candidate of ggplot2 using `devtools::install_github('tidyverse/ggplot2@v3.4.0-rc')` to test this out.

We plan to submit ggplot2 by the end of October and hope you can have a fix ready before then

Kind regards
Thomas

**Comment by finnlindgren** [comment]
I've traced the ggplot2 update issues for inlabru, https://github.com/inlabru-org/inlabru/issues/158, to `geom_polypath`. Happy to help look into it and test.

**Comment by mdsumner** [comment]
ok cool thanks for the headsup

**Comment by mdsumner** [comment]
@finnlindgren I"ve fixed in this branch: https://github.com/mdsumner/ggpolypath/tree/fix-linewidth

though, it would be better to use the newish facilities for holes and multipolygons in ggplot2 itself - but I'm sure you know that already - I haven't explored what the revdeps of ggpolypath are actually using yet.  

thanks!

**Comment by finnlindgren** [comment]
@mdsumner I can confirm that that resolved the https://github.com/inlabru-org/inlabru/issues/158 package check issues for inlabru. Thanks!

We started using `ggpolypath` (when installed) a while back, to avoid incorrect plotting of holes in `ggplot2::geom_polygon`. I haven't checked if the ggplot version has solved those issues (or if it wasn't meant to handle them, or if we didn't use it correctly).

**Comment by mdsumner** [comment]
thanks!  I'll fold into main branch and look at a release

**Comment by mdsumner** [comment]
ggpolypath 0.2.0 is on CRAN and robust to these coming changes, thanks!
